# Generated by Django 4.1.7 on 2023-03-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_customer_info_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='product',
        ),
    ]
