# Generated by Django 4.1.7 on 2023-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_customer_info_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='myid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
