# Generated by Django 4.1.7 on 2023-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_customer_info_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='myid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
