# Generated by Django 4.1.7 on 2023-03-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='notprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
