# Generated by Django 4.1.7 on 2023-03-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_notprice_alter_products_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='notprice',
            field=models.IntegerField(),
        ),
    ]
