# Generated by Django 4.1.7 on 2023-03-16 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_products_notprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='notprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
