# Generated by Django 4.1.7 on 2023-03-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_notprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='notprice',
        ),
    ]
