# Generated by Django 4.1.7 on 2023-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_products_notprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pricenot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
