# Generated by Django 4.1.7 on 2023-03-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_products_pricenot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pricenot',
        ),
    ]
