# Generated by Django 4.1.7 on 2023-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_products_pricenot'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='notprice',
            field=models.IntegerField(default=1),
        ),
    ]
