# Generated by Django 4.1.7 on 2023-03-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_products_notprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='quantity',
            new_name='الكمية',
        ),
    ]
