# Generated by Django 4.1.7 on 2023-03-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_quantity_customer_info_الكمية'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='الكمية',
            new_name='quantity',
        ),
    ]
