# Generated by Django 4.1.7 on 2023-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_الكمية_customer_info_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
