# Generated by Django 4.1.7 on 2023-03-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_emails_remove_customer_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
