# Generated by Django 4.1.7 on 2023-03-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_customer_info_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emails',
        ),
    ]
