# Generated by Django 4.1.7 on 2023-03-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
