# Generated by Django 4.1.7 on 2023-03-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_customer_info_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
