# Generated by Django 4.1.7 on 2023-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
