# Generated by Django 3.2.19 on 2023-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
