# Generated by Django 3.2.19 on 2023-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_products_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='situation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
