# Generated by Django 3.2.19 on 2023-06-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_customer_info_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='petitcontent',
            new_name='made',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
