# Generated by Django 3.2.19 on 2023-06-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_products_clasement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_infobyId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('myid', models.IntegerField(blank=True, null=True)),
                ('situation', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
