# Generated by Django 3.2.19 on 2023-06-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_rename_customer_infobyid_customer_infobycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_infobycart',
            name='myid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
