# Generated by Django 3.2.19 on 2023-06-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_customer_infobycart_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='myid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
