# Generated by Django 3.2.19 on 2023-06-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_customer_info_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='myid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
