# Generated by Django 3.2.19 on 2023-06-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_customer_info_myid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_infobycart',
            name='somme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
